
version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
