
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: monitor
  labels:
    app: backend
    app.kubernetes.io/part-of: monitoring-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
     containers:
  - name: backend
    image: ghcr.io/pavanGSP/monitoring-platform-backend:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
