
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: monitor
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
